version: "3.9"

services:
  app:
    image: node:22
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8081:3000"
    command: node server.js

